### ISSUE TITLE
[zh-TW] App name should be put inside "Open With" string

### ISSUE THREAD

**Issue by petercpg** [mozilla-l10n/focus-android-l10n#2]
String `menu_open_with` does not include the app name to open with, which violates the grammar in Chinese. We usually use 使用 {app} 開啟, literally 'Use {app} to Open'. 

The string itself should be changed to something like "Open With %s".

**Comment by petercpg** [comment]
ah.. @flodolo is it correct to report here, or should I report back to https://github.com/mozilla-mobile/focus-android ?

**Comment by flodolo** [comment]
Definitely report the issue in the official repo ;-)

**Comment by flodolo** [comment]
(now that I think of it, I should also disable issues in this project)

**Comment by flodolo** [comment]
@petercpg 
This is going to disappear soon, please report the issue in the code repository (and thanks for catching it).
